// This file is auto-generated by generate-downloads.js
// Do not edit manually - run: node generate-downloads.js

const changelogData = {
  "versions": [
    {
      "version": "2.0.1",
      "isLatest": true,
      "date": "",
      "new": [
        "Add clear Processing Logs button",
        "Auto delete all old Processing Logs on start",
        "Add gate 13 CVV with new Adyen encrypt system"
      ],
      "improved": [
        "Change adyen encrypt to local built-in, better performance and more accurate"
      ],
      "fixed": [
        "Fix wrong encrypt of gate 13 CVV"
      ],
      "breaking": []
    },
    {
      "version": "2.0.0",
      "isLatest": false,
      "date": "",
      "new": [
        "Add gate 31 CVV",
        "Bring Catpuccin theme",
        "Add support for Linux, Windows ARM64, MacOS Intel, MacOS ARM",
        "Add card number verification system before checking",
        "Switch interface management tool from Qt to Slint",
        "Upgrade CCN Tools to new version",
        "Bring CCN gates 1, 3 (Only keep the gates that definitely work)",
        "Add auto solve MTcaptcha system",
        "Add color distinction for Processing Logs",
        "Add copy support for Processing Logs"
      ],
      "improved": [
        "Rewrite from Python to Rust",
        "Rewrite all gates to Rust",
        "Remove redundant buttons",
        "Upgrade Multithreading system, greatly increase execution speed",
        "Remove dead code",
        "Update browser emulation system",
        "Reduce unnecessary vars"
      ],
      "fixed": [
        "Fix socks4a, socks5h connection errors",
        "Fix wrong udid when restarting on Windows VPS",
        "Fix captcha api v1 bug",
        "Fix random crash",
        "Fix None type() on gate 30 CVV",
        "Fix 407 error proxy authentication",
        "Fix invalid icon bug"
      ],
      "breaking": []
    }
  ]
};
