// This file is auto-generated by generate-downloads.js
// Do not edit manually - run: node generate-downloads.js

const changelogData = {
  "versions": [
    {
      "version": "2.0.7",
      "isLatest": true,
      "date": "17 December 2025",
      "new": [
        "Add Gate 5 CCN",
        "New \"📁 Results Folder\" button in Quick Actions section",
        "Files now save to ~/Documents/Gate-Rent/ instead of app bundle",
        "One-click access to open results folder in Finder/Explorer"
      ],
      "improved": [
        "Improved app icons and metadata",
        "Better macOS app bundling with proper .app structure",
        "Easy access to all saved files"
      ],
      "fixed": [
        "Disable gate 32 CVV due to it self down, will enable again when it back",
        "Disable gate 33 CVV due to recaptcha V3",
        "Disable gate 1 CCN due to new antibot",
        "Fixes issue where macOS users couldn't save config, proxies, and results"
      ],
      "breaking": []
    },
    {
      "version": "2.0.6",
      "isLatest": false,
      "date": "15 December 2025",
      "new": [
        "Add Gate 34 CVV",
        "Update popup now contain changelogs"
      ],
      "improved": [
        "New changelogs API",
        "Better return on proxy error"
      ],
      "fixed": [
        "Fixxed wrong response on gate 30 CVV",
        "Disable gate 31 CVV due to no longer good response"
      ],
      "breaking": []
    },
    {
      "version": "2.0.5",
      "isLatest": false,
      "date": "9 December 2025",
      "new": [
        "Add Panic Protection",
        "Added periodic timer to update elapsed time every second"
      ],
      "improved": [
        "Elapsed time now updates continuously during processing",
        "No more \"stuck forever\" panics from missing JSON fields",
        "No more crashes from unexpected API responses",
        "Continuous elapsed time updates during processing",
        "All errors return proper retry/failed messages",
        "Application stability significantly improved"
      ],
      "fixed": [
        "No longer freezes when cards take long to process",
        "Descriptive error messages for all failure cases"
      ],
      "breaking": []
    },
    {
      "version": "2.0.4",
      "isLatest": false,
      "date": "9 December 2025",
      "new": [
        "Added 600-second timeout protection for all gate operations",
        "Prevents infinite hangs with clear error messages",
        "Graceful timeout handling across all gates"
      ],
      "improved": [
        "Optimized Tokio runtime configuration with limited worker threads",
        "Increased stack size to 3MB to prevent stack overflow",
        "Main runtime: Limited to 4 worker threads (Intel Xeon compatible)",
        "Proxy validator: Optimized with 4 worker threads",
        "Implemented shared queue processing model"
      ],
      "fixed": [
        "Fixed hanging issues on Intel Xeon processors",
        "Resolved deep async call chain stack overflow issues"
      ],
      "breaking": []
    },
    {
      "version": "2.0.3",
      "isLatest": false,
      "date": "8 December 2025",
      "new": [
        "Add Gate 4 CCN, 32 CVV, 33 CVV",
        "Add Log Display customizations, now you can choose show BIN and BANK info, Time taken and my watermark or not",
        "Add Complete Popups"
      ],
      "improved": [
        "Improve retry logic, which will be fixed the problems on unstable networks"
      ],
      "fixed": [
        "Fix queries error on Gate 3 CCN",
        "Temporary disable Gate 13 CVV due to antibot"
      ],
      "breaking": []
    },
    {
      "version": "2.0.2",
      "isLatest": false,
      "date": "1 December 2025",
      "new": [
        "Add back gate 10 CVV",
        "Add retry layer for not unstable internet connections",
        "Add New Homepage",
        "Add Direct support chat in Telegram Channel"
      ],
      "improved": [
        "Reduce proxied requests size by removing unnecessary headers and compressing payloads. This optimization leads to faster response times and reduced bandwidth usage, enhancing overall performance for end-users.",
        "Reduce memory consumption by optimizing data structures and implementing efficient algorithms. This results in lower resource usage, allowing the application to run smoothly on devices with limited memory capacity.",
        "Enhance security by updating dependencies to their latest versions and patching known vulnerabilities. This ensures that the application remains protected against emerging threats and maintains user trust."
      ],
      "fixed": [
        "Fix invalid license key error that occurs for some users during activation process. This fix ensures that all valid license keys are recognized correctly, allowing users to activate their software without issues.",
        "Resolve crash issue when handling large datasets by optimizing memory management and improving error handling mechanisms. This fix enhances the stability of the application during intensive data processing tasks.",
        "Use .start_with() instead of .contains() to check for specific prefixes in strings. This change improves performance and accuracy when validating string formats, ensuring that only the intended prefixes are matched."
      ],
      "breaking": []
    },
    {
      "version": "2.0.1",
      "isLatest": false,
      "date": "28 November 2024",
      "new": [
        "Add clear Processing Logs button",
        "Auto delete all old Processing Logs on start",
        "Add gate 13 CVV with new Adyen encrypt system"
      ],
      "improved": [
        "Change adyen encrypt to local built-in, better performance and more accurate"
      ],
      "fixed": [
        "Fix wrong encrypt of gate 13 CVV"
      ],
      "breaking": []
    },
    {
      "version": "2.0.0",
      "isLatest": false,
      "date": "23 November 2024",
      "new": [
        "Add gate 31 CVV",
        "Bring Catpuccin theme",
        "Add support for Linux, Windows ARM64, MacOS Intel, MacOS ARM",
        "Add card number verification system before checking",
        "Switch interface management tool from Qt to Slint",
        "Upgrade CCN Tools to new version",
        "Bring CCN gates 1, 3 (Only keep the gates that definitely work)",
        "Add auto solve MTcaptcha system",
        "Add color distinction for Processing Logs",
        "Add copy support for Processing Logs"
      ],
      "improved": [
        "Rewrite from Python to Rust",
        "Rewrite all gates to Rust",
        "Remove redundant buttons",
        "Upgrade Multithreading system, greatly increase execution speed",
        "Remove dead code",
        "Update browser emulation system",
        "Reduce unnecessary vars"
      ],
      "fixed": [
        "Fix socks4a, socks5h connection errors",
        "Fix wrong udid when restarting on Windows VPS",
        "Fix captcha api v1 bug",
        "Fix random crash",
        "Fix None type() on gate 30 CVV",
        "Fix 407 error proxy authentication",
        "Fix invalid icon bug"
      ],
      "breaking": []
    }
  ]
};
