// This file is auto-generated by generate-downloads.js
// Do not edit manually - run: node generate-downloads.js

const changelogData = {
  "versions": [
    {
      "version": "2.0.2",
      "isLatest": true,
      "date": "1 December 2025",
      "new": [
        "Add back gate 10 CVV",
        "Add retry layer for not unstable internet connections",
        "Add New Homepage",
        "Add Direct support chat in Telegram Channel"
      ],
      "improved": [
        "Reduce proxied requests size by removing unnecessary headers and compressing payloads. This optimization leads to faster response times and reduced bandwidth usage, enhancing overall performance for end-users.",
        "Reduce memory consumption by optimizing data structures and implementing efficient algorithms. This results in lower resource usage, allowing the application to run smoothly on devices with limited memory capacity.",
        "Enhance security by updating dependencies to their latest versions and patching known vulnerabilities. This ensures that the application remains protected against emerging threats and maintains user trust."
      ],
      "fixed": [
        "Fix invalid license key error that occurs for some users during activation process. This fix ensures that all valid license keys are recognized correctly, allowing users to activate their software without issues.",
        "Resolve crash issue when handling large datasets by optimizing memory management and improving error handling mechanisms. This fix enhances the stability of the application during intensive data processing tasks.",
        "Use .start_with() instead of .contains() to check for specific prefixes in strings. This change improves performance and accuracy when validating string formats, ensuring that only the intended prefixes are matched."
      ],
      "breaking": []
    },
    {
      "version": "2.0.1",
      "isLatest": false,
      "date": "28 November 2024",
      "new": [
        "Add clear Processing Logs button",
        "Auto delete all old Processing Logs on start",
        "Add gate 13 CVV with new Adyen encrypt system"
      ],
      "improved": [
        "Change adyen encrypt to local built-in, better performance and more accurate"
      ],
      "fixed": [
        "Fix wrong encrypt of gate 13 CVV"
      ],
      "breaking": []
    },
    {
      "version": "2.0.0",
      "isLatest": false,
      "date": "23 November 2024",
      "new": [
        "Add gate 31 CVV",
        "Bring Catpuccin theme",
        "Add support for Linux, Windows ARM64, MacOS Intel, MacOS ARM",
        "Add card number verification system before checking",
        "Switch interface management tool from Qt to Slint",
        "Upgrade CCN Tools to new version",
        "Bring CCN gates 1, 3 (Only keep the gates that definitely work)",
        "Add auto solve MTcaptcha system",
        "Add color distinction for Processing Logs",
        "Add copy support for Processing Logs"
      ],
      "improved": [
        "Rewrite from Python to Rust",
        "Rewrite all gates to Rust",
        "Remove redundant buttons",
        "Upgrade Multithreading system, greatly increase execution speed",
        "Remove dead code",
        "Update browser emulation system",
        "Reduce unnecessary vars"
      ],
      "fixed": [
        "Fix socks4a, socks5h connection errors",
        "Fix wrong udid when restarting on Windows VPS",
        "Fix captcha api v1 bug",
        "Fix random crash",
        "Fix None type() on gate 30 CVV",
        "Fix 407 error proxy authentication",
        "Fix invalid icon bug"
      ],
      "breaking": []
    }
  ]
};
