// This file is auto-generated by generate-downloads.js
// Do not edit manually - run: node generate-downloads.js

const downloadsData = {
  "versions": [
    {
      "version": "2.0.14",
      "isLatest": true,
      "apps": [
        {
          "name": "Annnekkk Checker",
          "prefix": "Gate-Rent",
          "iconColor": "#89b4fa",
          "files": {
            "windows-x64.exe": 37789184,
            "windows-arm64.exe": 32700416,
            "macos-arm64.dmg": 11958643,
            "macos-x64.dmg": 13216214,
            "linux-x64": 36747416
          }
        }
      ]
    },
    {
      "version": "2.0.13",
      "isLatest": false,
      "apps": [
        {
          "name": "Annnekkk Checker",
          "prefix": "Gate-Rent",
          "iconColor": "#89b4fa",
          "files": {
            "windows-x64.exe": 37581312,
            "windows-arm64.exe": 32777728,
            "macos-arm64.dmg": 11953590,
            "macos-x64.dmg": 13556418,
            "linux-x64": 36670872
          }
        }
      ]
    },
    {
      "version": "2.0.12",
      "isLatest": false,
      "apps": [
        {
          "name": "Annnekkk Checker",
          "prefix": "Gate-Rent",
          "iconColor": "#89b4fa",
          "files": {
            "windows-x64.exe": 37988864,
            "windows-arm64.exe": 32821248,
            "macos-arm64.dmg": 12011073,
            "macos-x64.dmg": 13315787,
            "linux-x64": 36899800
          }
        }
      ]
    },
    {
      "version": "2.0.11",
      "isLatest": false,
      "apps": [
        {
          "name": "Annnekkk Checker",
          "prefix": "Gate-Rent",
          "iconColor": "#89b4fa",
          "files": {
            "windows-x64.exe": 36542976,
            "windows-arm64.exe": 31894016,
            "macos-arm64.dmg": 11741096,
            "macos-x64.dmg": 12977065,
            "linux-x64": 36281008
          }
        }
      ]
    },
    {
      "version": "2.0.10",
      "isLatest": false,
      "apps": [
        {
          "name": "Annnekkk Checker",
          "prefix": "Gate-Rent",
          "iconColor": "#89b4fa",
          "files": {
            "windows-x64.exe": 36420096,
            "windows-arm64.exe": 31798272,
            "macos-arm64.dmg": 11754655,
            "macos-x64.dmg": 12983942,
            "linux-x64": 36399760
          }
        }
      ]
    },
    {
      "version": "2.0.9",
      "isLatest": false,
      "apps": [
        {
          "name": "Annnekkk Checker",
          "prefix": "Gate-Rent",
          "iconColor": "#89b4fa",
          "files": {
            "windows-x64.exe": 36348928,
            "windows-arm64.exe": 31438848,
            "macos-arm64.dmg": 11414177,
            "macos-x64.dmg": 12575852,
            "linux-x64": 35646856
          }
        }
      ]
    },
    {
      "version": "2.0.8",
      "isLatest": false,
      "apps": [
        {
          "name": "Annnekkk Checker",
          "prefix": "Gate-Rent",
          "iconColor": "#89b4fa",
          "files": {
            "windows-x64.exe": 31026176,
            "windows-arm64.exe": 26884608,
            "macos-arm64.dmg": 12550270,
            "macos-x64.dmg": 13504251,
            "linux-x64": 44325112
          }
        }
      ]
    },
    {
      "version": "2.0.7",
      "isLatest": false,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 30351360,
            "windows-arm64.exe": 26249216,
            "macos-arm64.dmg": 12297583,
            "macos-x64.dmg": 13251079,
            "linux-x64": 43826080
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 30350848,
            "windows-arm64.exe": 26249216,
            "macos-arm64.dmg": 12298184,
            "macos-x64.dmg": 13251085,
            "linux-x64": 43826768
          }
        }
      ]
    },
    {
      "version": "2.0.6",
      "isLatest": false,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 30021120,
            "windows-arm64.exe": 26074624,
            "macos-arm64.dmg": 12192348,
            "macos-x64.dmg": 12903943,
            "linux-x64": 43608864
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 30021120,
            "windows-arm64.exe": 26075136,
            "macos-arm64.dmg": 12193827,
            "macos-x64.dmg": 12903749,
            "linux-x64": 43608120
          }
        }
      ]
    },
    {
      "version": "2.0.5",
      "isLatest": false,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 29983232,
            "windows-arm64.exe": 26108928,
            "macos-arm64.dmg": 12247049,
            "macos-x64.dmg": 12898937,
            "linux-x64": 43644416
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 29982720,
            "windows-arm64.exe": 26108928,
            "macos-arm64.dmg": 12246661,
            "macos-x64.dmg": 12899573,
            "linux-x64": 43644736
          }
        }
      ]
    },
    {
      "version": "2.0.4",
      "isLatest": false,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 29439488,
            "windows-arm64.exe": 25603584,
            "macos-arm64.dmg": 12107164,
            "macos-x64.dmg": 12743727,
            "linux-x64": 43308024
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 29438976,
            "windows-arm64.exe": 25603584,
            "macos-arm64.dmg": 12107159,
            "macos-x64.dmg": 12742821,
            "linux-x64": 43306424
          }
        }
      ]
    },
    {
      "version": "2.0.3",
      "isLatest": false,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 32782336,
            "windows-arm64.exe": 28468736,
            "macos-arm64.dmg": 13062437,
            "macos-x64.dmg": 13800181,
            "linux-x64": 45865056
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 32781824,
            "windows-arm64.exe": 28468736,
            "macos-arm64.dmg": 13061970,
            "macos-x64.dmg": 13799580,
            "linux-x64": 45865136
          }
        }
      ]
    },
    {
      "version": "2.0.2",
      "isLatest": false,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 31578624,
            "windows-arm64.exe": 27392512,
            "macos-arm64.dmg": 12692629,
            "macos-x64.dmg": 13413140,
            "linux-x64": 44807856
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 31578624,
            "windows-arm64.exe": 27392512,
            "macos-arm64.dmg": 12693077,
            "macos-x64.dmg": 13413271,
            "linux-x64": 44806128
          }
        }
      ]
    },
    {
      "version": "2.0.1",
      "isLatest": false,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 27760640,
            "windows-arm64.exe": 24159744,
            "macos-arm64.dmg": 11227444,
            "macos-x64.dmg": 11819485,
            "linux-x64": 40926336
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 27760640,
            "windows-arm64.exe": 24160768,
            "macos-arm64.dmg": 11228718,
            "macos-x64.dmg": 11818097,
            "linux-x64": 40926344
          }
        }
      ]
    },
    {
      "version": "2.0.0",
      "isLatest": false,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 27049472,
            "windows-arm64.exe": 23630336,
            "macos-arm64.dmg": 10983626,
            "macos-x64.dmg": 11540282,
            "linux-x64": 40240776
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 27049472,
            "windows-arm64.exe": 23630336,
            "macos-arm64.dmg": 10984709,
            "macos-x64.dmg": 11540398,
            "linux-x64": 40240776
          }
        }
      ]
    }
  ],
  "platforms": [
    {
      "name": "Windows x64",
      "suffix": "windows-x64.exe",
      "description": "For 64-bit Windows systems",
      "icon": "windows"
    },
    {
      "name": "Windows ARM64",
      "suffix": "windows-arm64.exe",
      "description": "For ARM64 Windows systems",
      "icon": "windows"
    },
    {
      "name": "macOS ARM64",
      "suffix": "macos-arm64.dmg",
      "description": "For Apple Silicon (M1/M2/M3)",
      "icon": "macos"
    },
    {
      "name": "macOS x64",
      "suffix": "macos-x64.dmg",
      "description": "For Intel-based Macs",
      "icon": "macos"
    },
    {
      "name": "Linux x64",
      "suffix": "linux-x64",
      "description": "For 64-bit Linux systems",
      "icon": "linux"
    }
  ]
};
