// This file is auto-generated by generate-downloads.js
// Do not edit manually - run: node generate-downloads.js

const downloadsData = {
  "versions": [
    {
      "version": "2.0.1",
      "isLatest": true,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 27760640,
            "windows-arm64.exe": 24159744,
            "macos-arm64.dmg": 11227444,
            "macos-x64.dmg": 11819485,
            "linux-x64": 40926336
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 27760640,
            "windows-arm64.exe": 24160768,
            "macos-arm64.dmg": 11228718,
            "macos-x64.dmg": 11818097,
            "linux-x64": 40926344
          }
        }
      ]
    },
    {
      "version": "2.0.0",
      "isLatest": false,
      "apps": [
        {
          "name": "CCN Checker",
          "prefix": "ccn-Checker",
          "iconColor": "#cba6f7",
          "files": {
            "windows-x64.exe": 27049472,
            "windows-arm64.exe": 23630336,
            "macos-arm64.dmg": 10983626,
            "macos-x64.dmg": 11540282,
            "linux-x64": 40240776
          }
        },
        {
          "name": "CVV Checker",
          "prefix": "cvv-Checker",
          "iconColor": "#f5c2e7",
          "files": {
            "windows-x64.exe": 27049472,
            "windows-arm64.exe": 23630336,
            "macos-arm64.dmg": 10984709,
            "macos-x64.dmg": 11540398,
            "linux-x64": 40240776
          }
        }
      ]
    }
  ],
  "platforms": [
    {
      "name": "Windows x64",
      "suffix": "windows-x64.exe",
      "description": "For 64-bit Windows systems",
      "icon": "windows"
    },
    {
      "name": "Windows ARM64",
      "suffix": "windows-arm64.exe",
      "description": "For ARM64 Windows systems",
      "icon": "windows"
    },
    {
      "name": "macOS ARM64",
      "suffix": "macos-arm64.dmg",
      "description": "For Apple Silicon (M1/M2/M3)",
      "icon": "macos"
    },
    {
      "name": "macOS x64",
      "suffix": "macos-x64.dmg",
      "description": "For Intel-based Macs",
      "icon": "macos"
    },
    {
      "name": "Linux x64",
      "suffix": "linux-x64",
      "description": "For 64-bit Linux systems",
      "icon": "linux"
    }
  ]
};
